#define GSTDDEC_FSE_TABLE_CELL_BASELINE_OFFSET	0
#define GSTDDEC_FSE_TABLE_CELL_BASELINE_MASK	0xffff

#define GSTDDEC_FSE_TABLE_CELL_SYM_OFFSET		24
#define GSTDDEC_FSE_TABLE_CELL_SYM_MASK			0xff

#define GSTDDEC_FSE_TABLE_CELL_NUMBITS_OFFSET	16
#define GSTDDEC_FSE_TABLE_CELL_NUMBITS_MASK		0xff
