#define GSTDDEC_VVEC_SIZE	((GSTDDEC_FORMAT_WIDTH + GSTDDEC_VECTOR_WIDTH - 1) / GSTDDEC_VECTOR_WIDTH)

#define GSTDDEC_STATIC_MAX(a, b) (((a) > (b)) ? (a) : (b))
#define GSTDDEC_STATIC_MIN(a, b) (((a) < (b)) ? (a) : (b))

#define GSTDDEC_MAX_ANY_SYMBOL (1 + GSTDDEC_STATIC_MAX(GSTDDEC_STATIC_MAX(GSTDDEC_STATIC_MAX(GSTD_MAX_HUFFMAN_WEIGHT, GSTD_MAX_OFFSET_CODE), GSTD_MAX_MATCH_LENGTH_CODE), GSTD_MAX_LIT_LENGTH_CODE))
#define GSTDDEC_MAX_ANY_ACCURACY_LOG (GSTDDEC_STATIC_MAX(GSTDDEC_STATIC_MAX(GSTDDEC_STATIC_MAX(GSTD_MAX_HUFFMAN_WEIGHT_ACCURACY_LOG, GSTD_MAX_OFFSET_ACCURACY_LOG), GSTD_MAX_MATCH_LENGTH_ACCURACY_LOG), GSTD_MAX_LIT_LENGTH_ACCURACY_LOG))

#define GSTDDEC_FSETAB_HUFF_WEIGHT_START	0
#define GSTDDEC_FSETAB_HUFF_WEIGHT_SIZE		(1 << GSTD_MAX_HUFFMAN_WEIGHT_ACCURACY_LOG)

#define GSTDDEC_FSETAB_OFFSET_START			(GSTDDEC_FSETAB_HUFF_WEIGHT_START + GSTDDEC_FSETAB_HUFF_WEIGHT_SIZE)
#define GSTDDEC_FSETAB_OFFSET_SIZE			(1 << GSTD_MAX_OFFSET_ACCURACY_LOG)

#define GSTDDEC_FSETAB_MATCH_LENGTH_START	(GSTDDEC_FSETAB_OFFSET_START + GSTDDEC_FSETAB_OFFSET_SIZE)
#define GSTDDEC_FSETAB_MATCH_LENGTH_SIZE	(1 << GSTD_MAX_MATCH_LENGTH_ACCURACY_LOG)

#define GSTDDEC_FSETAB_LIT_LENGTH_START		(GSTDDEC_FSETAB_MATCH_LENGTH_START + GSTDDEC_FSETAB_MATCH_LENGTH_SIZE)
#define GSTDDEC_FSETAB_LIT_LENGTH_SIZE		(1 << GSTD_MAX_LIT_LENGTH_ACCURACY_LOG)

#define GSTDDEC_FSE_TABLE_DATA_SIZE			(GSTDDEC_FSETAB_LIT_LENGTH_START + GSTDDEC_FSETAB_LIT_LENGTH_SIZE)

#define GSTDDEC_IS_WIDER_THAN_FORMAT	(GSTDDEC_VECTOR_WIDTH > GSTDDEC_FORMAT_WIDTH)


struct DecompressorState
{
	uint32_t readPos;
	uint32_t uncompressedBytes;
	uint32_t uncompressedBytesAvailable;

	vuint64_t bitstreamBits[GSTDDEC_VVEC_SIZE];
	vuint32_t bitstreamAvailable[GSTDDEC_VVEC_SIZE];

	vuint32_t fseState[GSTDDEC_VVEC_SIZE];
	vuint32_t fseDrainLevel[GSTDDEC_VVEC_SIZE];

	uint32_t litRLEByte;
};

struct GroupSharedDecompressorState
{
	uint32_t packedHuffmanWeights[64];	// 4 bits each

	uint32_t probTemps[1 << GSTDDEC_MAX_ANY_ACCURACY_LOG];

	uint32_t fseCells[GSTDDEC_FSE_TABLE_DATA_SIZE];
};

#define GSTDDEC_FSE_TABLE_CELL_BASELINE_OFFSET	0
#define GSTDDEC_FSE_TABLE_CELL_BASELINE_MASK	0xffff

#define GSTDDEC_FSE_TABLE_CELL_SYM_OFFSET		24
#define GSTDDEC_FSE_TABLE_CELL_SYM_MASK			0xff

#define GSTDDEC_FSE_TABLE_CELL_NUMBITS_OFFSET	16
#define GSTDDEC_FSE_TABLE_CELL_NUMBITS_MASK		0xff
